--DATA CLEANING
  -- Checking NULL values 
     SELECT * FROM retail_sales
           WHERE 
           sale_date IS NULL OR sale_time IS NULL OR customer_id IS NULL OR 
           gender IS NULL OR age IS NULL OR category IS NULL OR 
           quantity IS NULL OR price_per_unit IS NULL OR cogs IS NULL;

   --Deleting NULL values 
     DELETE FROM retail_sales
           WHERE 
           sale_date IS NULL OR sale_time IS NULL OR customer_id IS NULL OR 
           gender IS NULL OR age IS NULL OR category IS NULL OR 
           quantity IS NULL OR price_per_unit IS NULL OR cogs IS NULL;

--DATA EXPLORATION 

--Total number of sales
SELECT COUNT(*) FROM retail_sales ;

--Number of unique customers
SELECT COUNT(DISTINCT customer_id) FROM retail_sales;

--Types of categories
SELECT DISTINCT category FROM retail_sales;

--Total Sale value
SELECT SUM(total_sale) AS total_sales FROM retail_sales;
--Average, minimum, and maximum sales per transaction
SELECT 
    AVG(total_sale) AS avg_sale, 
    MIN(total_sale) AS min_sale, 
    MAX(total_sale) AS max_sale
FROM retail_sales;

--Customer Demography
--Distribution of Customers by gender
SELECT gender, COUNT(DISTINCT customer_id) AS customer_count FROM retail_sales GROUP BY gender;
--Age group Distribution
SELECT 
    CASE 
        WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 40 THEN '26-40'
        WHEN age BETWEEN 41 AND 60 THEN '41-60'
        ELSE 'Above 60'
    END AS age_group, 
    COUNT(customer_id) AS customer_count
FROM retail_sales
GROUP BY 
    CASE 
        WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 40 THEN '26-40'
        WHEN age BETWEEN 41 AND 60 THEN '41-60'
        ELSE 'Above 60'
    END;

--SALES PERFORMANCE ANALYSIS

--Total sales and quantity sold by category.
SELECT 
    category, 
    SUM(quantity) AS total_quantity, 
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY category;

--Total Sales by date
SELECT 
    sale_date, 
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY sale_date
ORDER BY sale_date;

--Monthly Sales Trend
SELECT 
    YEAR(sale_date) AS year, 
    MONTH(sale_date) AS month, 
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY YEAR(sale_date), MONTH(sale_date)
ORDER BY year, month;

--Peak Sale Hours
SELECT 
    DATEPART(HOUR, sale_time) AS hour, 
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY DATEPART(HOUR, sale_time)
ORDER BY hour;

--CUSTOMER BEHAVIOUR ANALYSIS
--Top 10 customers by Total Sales
SELECT TOP 10
    customer_id, 
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY customer_id
ORDER BY total_sales DESC;

--Number of transactions per customer
SELECT 
    customer_id, 
    COUNT(transactions_id) AS transaction_count
FROM retail_sales
GROUP BY customer_id
ORDER BY transaction_count DESC;

--PROFITIBILITY ANALYSIS
--Profit by Cateogory
SELECT 
    category, 
    SUM(total_sale - cogs) AS total_profit
FROM retail_sales
GROUP BY category
ORDER BY total_profit DESC; 

--Total Profit generated by each Customer
SELECT 
    customer_id, 
    SUM(total_sale - cogs) AS total_profit
FROM retail_sales
GROUP BY customer_id
ORDER BY total_profit DESC;

--INVENTORY AND PRODUCT ANALYSIS
  --Most frequent sold categories
    SELECT 
          category, 
          SUM(quantity) AS total_quantity
    FROM retail_sales
    GROUP BY category
    ORDER BY total_quantity DESC;

  --Average price per unit by category.
    SELECT 
        category, 
        AVG(price_per_unit) AS avg_price
     FROM retail_sales
     GROUP BY category;

--ANOMOLY DETECTION
 --Identify transactions with unusually high or low total sales.
  SELECT *
     FROM retail_sales
     WHERE total_sale > (SELECT AVG(total_sale) + 3 * STDEV(total_sale) FROM retail_sales)
     OR total_sale < (SELECT AVG(total_sale) - 3 * STDEV(total_sale) FROM retail_sales);

 --Check for transactions where COGS is higher than total sales.
  SELECT *
    FROM retail_sales
    WHERE cogs > total_sale;

--Analyze sales trends over time using SQL window functions:
  SELECT 
    sale_date, 
    SUM(total_sale) AS daily_sales,
    AVG(SUM(total_sale)) OVER (ORDER BY sale_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_avg_7_days
   FROM retail_sales
   GROUP BY sale_date
   ORDER BY sale_date;

--Categorize customers into high-value, medium-value, and low-value based on total sales.
  SELECT 
     customer_id, 
     SUM(total_sale) AS total_sales,
     CASE 
        WHEN SUM(total_sale) > 5000 THEN 'High-Value'
        WHEN SUM(total_sale) BETWEEN 1000 AND 5000 THEN 'Medium-Value'
        ELSE 'Low-Value'
     END AS customer_segment
   FROM retail_sales_
   GROUP BY customer_id;

